include:
  - project: graphaware/devops/gitlab-ci-templates
    file: gitlab-ci-templates.yml

stages:
  - deploy
  - postDeploy

bumpVersion:
  extends: .frameworkVersionBump
  variables:
    MAVEN_CLI_OPTS: "-s .m2/settings.xml"
  stage: deploy
  only:
    refs:
      - CICD
    variables:
      - $PARENT_VERSION

uploadArtifact:
  extends: .uploadToS3
  stage: postDeploy
  dependencies:
    - bumpVersion
  variables:
    JAR_NAME: neo4j-to-elasticsearch
  only:
    refs:
      - CICD
    variables:
      - $PARENT_VERSION