include:
  - project: graphaware/devops/gitlab-ci-templates
    file: gitlab-ci-templates.yml

stages:
  - deploy
  - postDeploy

bumpVersion:
  extends: .frameworkVersionBump
  stage: deploy
  when: delayed
  start_in: 30 minutes

uploadArtifact:
  extends: .uploadToS3
  stage: postDeploy
  dependencies:
    - bumpVersion
  variables:
    JAR_NAME: neo4j-to-elasticsearch
  only:
    refs:
      - master
    variables:
      - $PARENT_VERSION